version: '3.8'
services:
 pg_mopdocs_be:
   container_name: pg_mopdocs_be
   image: postgres:13.5-alpine
   restart: always
   environment:
     POSTGRES_DB: filemanagerdb
     POSTGRES_USER: admin
     POSTGRES_PASSWORD: secret
     PGDATA: /var/lib/postgresql/data
   ports:
     - "5432:5432"
   volumes:
     - db-data:/var/lib/postgresql/data

 pgadmin_mopdocs_be:
   container_name: pgadmin_mopdocs_be
   image: dpage/pgadmin4:5.5
   restart: always
   environment:
     PGADMIN_DEFAULT_EMAIL: admin@admin.com
     PGADMIN_DEFAULT_PASSWORD: secret
     PGADMIN_LISTEN_PORT: 80
   ports:
     - "8080:80"
   volumes:
     - pgadmin-data:/var/lib/pgadmin
volumes:
 db-data:
 pgadmin-data: